apiVersion: apps/v1
kind: Deployment
metadata:
  name: sessions-ms-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: backend
      ms: sessions
  template:
    metadata:
      labels:
        tier: backend
        ms: sessions
    spec:
      containers:
        - name: sesssions-microservice
          image: thhdemo.azurecr.io/sessions-ms:latest
          env:
            - name: APPINSIGHTS_INSTRUMENTATIONKEY
              valueFrom:
                secretKeyRef:
                  name: backendsecret
                  key: ai_key
            - name: ASPNETCORE_URLS
              value: http://*:8080
            - name: DbConnectionString
              valueFrom:
                secretKeyRef:
                  name: backendsecret
                  key: db
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /api/meta/healthy
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 4
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/meta/ready
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 4
            periodSeconds: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "64m"
            limits:
              memory: "96Mi"
              cpu: "125m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: votings-ms-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: backend
      ms: votings
  template:
    metadata:
      name: votings-ms
      labels:
        tier: backend
        ms: votings
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
        kubernetes.io/role: agent
        type: virtual-kubelet
      tolerations:
        - key: virtual-kubelet.io/provider
          operator: Equal
          value: azure
          effect: NoSchedule
      imagePullSecrets:
        - name: acr-auth
      containers:
        - name: votings-microservice
          image: thhdemo.azurecr.io/votings-ms:latest
          env:
            - name: APPINSIGHTS_INSTRUMENTATIONKEY
              valueFrom:
                secretKeyRef:
                  name: backendsecret
                  key: ai_key
            - name: ASPNETCORE_URLS
              value: http://*:8080
            - name: DbConnectionString
              valueFrom:
                secretKeyRef:
                  name: backendsecret
                  key: db
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /api/meta/healthy
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 4
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/meta/ready
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 4
            periodSeconds: 5
          resources:
            requests:
              memory: "1G"
              cpu: "1"
            limits:
              memory: "1G"
              cpu: "1"
